// Clearing of table not working on multiple shifts and gives error
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dhruv
 */
public class generate_report extends javax.swing.JFrame {

    /**
     * Creates new form generate_report
     */
    public generate_report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TFo_cust = new javax.swing.JTextField();
        TFo_item = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TFo_status = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Main_Menu_Button1 = new javax.swing.JButton();
        CustID_Filter_Button = new javax.swing.JButton();
        ItemOrdered_Go_Button = new javax.swing.JButton();
        Status_Go_Button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TFo_date = new javax.swing.JTextField();
        Date_Filter_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Report Generation");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Edwardian Script ITC", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Generate Report  [Orders]");
        jLabel2.setOpaque(true);

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 204)));
        jTable1.setFont(new java.awt.Font("Avignon Pro", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Customer ID", "Item Ordered", "Quantity", "Price", "Total", "Date &Time", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Filter by Customer Id:");

        TFo_cust.setFont(new java.awt.Font("Avignon Pro", 0, 18)); // NOI18N

        TFo_item.setFont(new java.awt.Font("Avignon Pro", 0, 18)); // NOI18N
        TFo_item.setText("Try to be accurate");
        TFo_item.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFo_itemFocusGained(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Filter by Item Ordered:");

        TFo_status.setFont(new java.awt.Font("Avignon Pro", 0, 18)); // NOI18N
        TFo_status.setText("[ X / O ]");
        TFo_status.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFo_statusFocusGained(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Filter by Status :");

        Main_Menu_Button1.setFont(new java.awt.Font("Avignon Pro", 0, 18)); // NOI18N
        Main_Menu_Button1.setText("Main Menu");
        Main_Menu_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_Menu_Button1ActionPerformed(evt);
            }
        });

        CustID_Filter_Button.setFont(new java.awt.Font("Avignon Pro", 0, 18)); // NOI18N
        CustID_Filter_Button.setText("Filter");
        CustID_Filter_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustID_Filter_ButtonActionPerformed(evt);
            }
        });

        ItemOrdered_Go_Button.setFont(new java.awt.Font("Avignon Pro", 0, 18)); // NOI18N
        ItemOrdered_Go_Button.setText("Go !");
        ItemOrdered_Go_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemOrdered_Go_ButtonActionPerformed(evt);
            }
        });

        Status_Go_Button.setFont(new java.awt.Font("Avignon Pro", 0, 18)); // NOI18N
        Status_Go_Button.setText("Go !");
        Status_Go_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Status_Go_ButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Filter by Date :");

        TFo_date.setFont(new java.awt.Font("Avignon Pro", 0, 18)); // NOI18N
        TFo_date.setText("[ yyyy-mm-dd ]");
        TFo_date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFo_dateFocusGained(evt);
            }
        });

        Date_Filter_Button.setFont(new java.awt.Font("Avignon Pro", 0, 18)); // NOI18N
        Date_Filter_Button.setText("Filter");
        Date_Filter_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Date_Filter_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TFo_date, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Date_Filter_Button)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TFo_status, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Status_Go_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Main_Menu_Button1)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TFo_cust, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CustID_Filter_Button))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TFo_item, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ItemOrdered_Go_Button)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFo_cust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustID_Filter_Button))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TFo_item, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemOrdered_Go_Button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TFo_status, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Status_Go_Button)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Main_Menu_Button1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(TFo_date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date_Filter_Button))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Main_Menu_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_Menu_Button1ActionPerformed
        // TODO add your handling code here:
        Main_Menu mm=new Main_Menu();
        mm.setVisible(true);
        dispose();
    }//GEN-LAST:event_Main_Menu_Button1ActionPerformed

    private void CustID_Filter_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustID_Filter_ButtonActionPerformed
        // TODO add your handling code here:
        
        // Search by Customer
        
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        //dtm.removeTableModelListener(jTable1);
        int rc=dtm.getRowCount();
        System.out.println(rc);
        if(rc>0)
        {
            for(int i=0;i<rc;i++)
            {
                dtm.removeRow(i);
            }
        }
        String check=TFo_cust.getText();
        if(check.isBlank())
        {
            JOptionPane.showMessageDialog(this,"Please Enter the Customer ID");
        }
        else
        {
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe","root","dhruv");
            Statement stmt=(Statement)con.createStatement();
            int o_cust=Integer.parseInt(TFo_cust.getText());
            
            String query="select * from orders where o_cust='"+o_cust+"';";
            //dml=insert,update,delete =>  executeUpdate(qry)
            //ddl=create,alter,drop =>  execute(qry)
            //select =>  executeQuery(qry)
            ResultSet rs=stmt.executeQuery(query);
            int count=0;
            while(rs.next())
            {
                //    o_id , o_cust , o_item , o_qty , o_price , o_total , o_date , o_status 
                count++;
                int DBo_id=rs.getInt("o_id");
                int DBo_cust=rs.getInt("o_cust");
                String DBo_item=rs.getString("o_item");
                int DBo_qty=rs.getInt("o_qty");
                float DBo_price=rs.getFloat("o_price");
                float DBo_total=rs.getFloat("o_total");
                String DBo_date=rs.getString("o_date");
                String DBo_status=rs.getString("o_status");
                //to add data in table 
                dtm.addRow(new Object[] {DBo_id,DBo_cust,DBo_item,DBo_qty,DBo_price,DBo_total,DBo_date,DBo_status});
            }
            rs.close();
            stmt.close();
            con.close();
        }        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        }
        
    }//GEN-LAST:event_CustID_Filter_ButtonActionPerformed

    private void ItemOrdered_Go_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemOrdered_Go_ButtonActionPerformed
        // TODO add your handling code here:
        
        // Search by Item ordered
        
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        //dtm.removeTableModelListener(jTable1);
        int rc=dtm.getRowCount();
        if(rc>0)
        {
            for(int i=0;i<rc;i++)
            {
                dtm.removeRow(i);
            }
        }
        /*String check=TFo_cust.getText();
        String to_check="Try to be accurate";
        if(check.equalsIgnoreCase(to_check))
        {
            JOptionPane.showMessageDialog(this,"Please Enter the Item Ordered");
        }
        else
        {*/
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe","root","dhruv");
            Statement stmt=(Statement)con.createStatement();
            String o_item=TFo_item.getText();
            String o_item2="%"+o_item+"%";
            
            String query="select * from orders where o_item like '"+o_item2+"';";
            //dml=insert,update,delete =>  executeUpdate(qry)
            //ddl=create,alter,drop =>  execute(qry)
            //select =>  executeQuery(qry)
            ResultSet rs=stmt.executeQuery(query);
            int count=0;
            while(rs.next())
            {
                //    o_id , o_cust , o_item , o_qty , o_price , o_total , o_date , o_status 
                count++;
                int DBo_id=rs.getInt("o_id");
                int DBo_cust=rs.getInt("o_cust");
                String DBo_item=rs.getString("o_item");
                int DBo_qty=rs.getInt("o_qty");
                float DBo_price=rs.getFloat("o_price");
                float DBo_total=rs.getFloat("o_total");
                String DBo_date=rs.getString("o_date");
                String DBo_status=rs.getString("o_status");
                //to add data in table 
                dtm.addRow(new Object[] {DBo_id,DBo_cust,DBo_item,DBo_qty,DBo_price,DBo_total,DBo_date,DBo_status});
            }
            rs.close();
            stmt.close();
            con.close();
        }        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        //}
        
    }//GEN-LAST:event_ItemOrdered_Go_ButtonActionPerformed

    private void Status_Go_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Status_Go_ButtonActionPerformed
        // TODO add your handling code here:
        
        // Search by Status of Payment
        
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        //dtm.removeTableModelListener(jTable1);
        int rc=dtm.getRowCount();
        if(rc>0)
        {
            for(int i=0;i<rc;i++)
            {
                dtm.removeRow(i);
            }
        }
        /*String check=TFo_status.getText();
        String to_check="  "; insert the String in staus TF
        if(check.equalsIgnoreCase(to_check))
        {
            JOptionPane.showMessageDialog(this,"Please Enter the Status");
        }
        else
        {*/
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe","root","dhruv");
            Statement stmt=(Statement)con.createStatement();
            String o_status=TFo_status.getText();
            
            
            String query="select * from orders where o_status='"+o_status+"';";
            //dml=insert,update,delete =>  executeUpdate(qry)
            //ddl=create,alter,drop =>  execute(qry)
            //select =>  executeQuery(qry)
            ResultSet rs=stmt.executeQuery(query);
            int count=0;
            while(rs.next())
            {
                //    o_id , o_cust , o_item , o_qty , o_price , o_total , o_date , o_status 
                count++;
                int DBo_id=rs.getInt("o_id");
                int DBo_cust=rs.getInt("o_cust");
                String DBo_item=rs.getString("o_item");
                int DBo_qty=rs.getInt("o_qty");
                float DBo_price=rs.getFloat("o_price");
                float DBo_total=rs.getFloat("o_total");
                String DBo_date=rs.getString("o_date");
                String DBo_status=rs.getString("o_status");
                //to add data in table 
                dtm.addRow(new Object[] {DBo_id,DBo_cust,DBo_item,DBo_qty,DBo_price,DBo_total,DBo_date,DBo_status});
            }
            rs.close();
            stmt.close();
            con.close();
        }        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        //}
    }//GEN-LAST:event_Status_Go_ButtonActionPerformed

    private void Date_Filter_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Date_Filter_ButtonActionPerformed
        // TODO add your handling code here:
        
        // Search by DATE ordered on
        
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        //dtm.removeTableModelListener(jTable1);
        int rc=dtm.getRowCount();
        if(rc>0)
        {
            for(int i=0;i<rc;i++)
            {
                dtm.removeRow(i);
            }
        }
        /*String check=TFo_date.getText();
        String to_check=" "; insert the string in date TF
        if(check.equalsIgnoreCase(to_check))
        {
            JOptionPane.showMessageDialog(this,"Please Enter the Date");
        }
        else
        {*/
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe","root","dhruv");
            Statement stmt=(Statement)con.createStatement();
            String o_date=TFo_date.getText();
            String o_date2="%"+o_date+"%";
            
            String query="select * from orders where o_date like '"+o_date2+"';";
            //dml=insert,update,delete =>  executeUpdate(qry)
            //ddl=create,alter,drop =>  execute(qry)
            //select =>  executeQuery(qry)
            ResultSet rs=stmt.executeQuery(query);
            int count=0;
            while(rs.next())
            {
                //    o_id , o_cust , o_item , o_qty , o_price , o_total , o_date , o_status 
                count++;
                int DBo_id=rs.getInt("o_id");
                int DBo_cust=rs.getInt("o_cust");
                String DBo_item=rs.getString("o_item");
                int DBo_qty=rs.getInt("o_qty");
                float DBo_price=rs.getFloat("o_price");
                float DBo_total=rs.getFloat("o_total");
                String DBo_date=rs.getString("o_date");
                String DBo_status=rs.getString("o_status");
                //to add data in table 
                dtm.addRow(new Object[] {DBo_id,DBo_cust,DBo_item,DBo_qty,DBo_price,DBo_total,DBo_date,DBo_status});
            }
            rs.close();
            stmt.close();
            con.close();
        }        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        //}
    }//GEN-LAST:event_Date_Filter_ButtonActionPerformed

    private void TFo_itemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFo_itemFocusGained
        // TODO add your handling code here:
        TFo_item.setText("");
    }//GEN-LAST:event_TFo_itemFocusGained

    private void TFo_statusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFo_statusFocusGained
        // TODO add your handling code here:
        TFo_status.setText("");
    }//GEN-LAST:event_TFo_statusFocusGained

    private void TFo_dateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFo_dateFocusGained
        // TODO add your handling code here:
        TFo_date.setText("");
    }//GEN-LAST:event_TFo_dateFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generate_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generate_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generate_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generate_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new generate_report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CustID_Filter_Button;
    private javax.swing.JButton Date_Filter_Button;
    private javax.swing.JButton ItemOrdered_Go_Button;
    private javax.swing.JButton Main_Menu_Button1;
    private javax.swing.JButton Status_Go_Button;
    private javax.swing.JTextField TFo_cust;
    private javax.swing.JTextField TFo_date;
    private javax.swing.JTextField TFo_item;
    private javax.swing.JTextField TFo_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
