
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dhruv
 */
public class place_order extends javax.swing.JFrame {

    /**
     * Creates new form place_order
     */
    public place_order() {
        initComponents();
    }
    java.sql.Statement stmt=null;
    ResultSet rs=null;
    Connection con;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CBcategory = new javax.swing.JComboBox<>();
        CBfood = new javax.swing.JComboBox<>();
        CBqty = new javax.swing.JComboBox<>();
        CBprice = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TFo_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TFo_cust = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        Clear_Button = new javax.swing.JButton();
        Main_Menu_Button1 = new javax.swing.JButton();
        place_order_button = new javax.swing.JButton();
        Proceed_Button = new javax.swing.JButton();
        Check_Price_Button = new javax.swing.JButton();
        TFprice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lets Eat :)");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Edwardian Script ITC", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Place  Your Order !  ");
        jLabel3.setOpaque(true);

        CBcategory.setFont(new java.awt.Font("Avignon Pro", 2, 18)); // NOI18N
        CBcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------------Select------------------", "Starters", "Sandwiches", "Pizza", "Pasta", "Coffee/Tea", "Shakes", "Juice", " " }));
        CBcategory.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CBcategoryFocusLost(evt);
            }
        });
        CBcategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CBcategoryMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CBcategoryMousePressed(evt);
            }
        });
        CBcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBcategoryActionPerformed(evt);
            }
        });

        CBfood.setFont(new java.awt.Font("Avignon Pro", 2, 18)); // NOI18N
        CBfood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------------Select------------------" }));
        CBfood.setEnabled(false);
        CBfood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CBfoodMouseClicked(evt);
            }
        });

        CBqty.setFont(new java.awt.Font("Avignon Pro", 2, 18)); // NOI18N
        CBqty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        CBqty.setEnabled(false);

        CBprice.setFont(new java.awt.Font("Avignon Pro", 2, 18)); // NOI18N
        CBprice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------Select---------" }));
        CBprice.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Category :");

        jLabel2.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Qty :");

        jLabel4.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Food Item :");

        jLabel5.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price :");

        jLabel6.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Order Id :");

        TFo_id.setEditable(false);
        TFo_id.setFont(new java.awt.Font("Avignon Pro", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Customer Id :");

        TFo_cust.setFont(new java.awt.Font("Avignon Pro", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Payment ?");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Avignon Pro", 0, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Now");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Avignon Pro", 0, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Later");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee_cappuccino_LA.jpg"))); // NOI18N
        jLabel10.setOpaque(true);

        Clear_Button.setFont(new java.awt.Font("Avignon Pro", 0, 18)); // NOI18N
        Clear_Button.setText("Clear ");
        Clear_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_ButtonActionPerformed(evt);
            }
        });

        Main_Menu_Button1.setFont(new java.awt.Font("Avignon Pro", 0, 18)); // NOI18N
        Main_Menu_Button1.setText("Main Menu");
        Main_Menu_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_Menu_Button1ActionPerformed(evt);
            }
        });

        place_order_button.setFont(new java.awt.Font("Avignon Pro", 0, 18)); // NOI18N
        place_order_button.setText("LESSGOO");
        place_order_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place_order_buttonActionPerformed(evt);
            }
        });

        Proceed_Button.setBackground(new java.awt.Color(255, 255, 51));
        Proceed_Button.setFont(new java.awt.Font("Avignon Pro", 0, 18)); // NOI18N
        Proceed_Button.setForeground(new java.awt.Color(51, 51, 51));
        Proceed_Button.setText("Proceed");
        Proceed_Button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Proceed_Button.setOpaque(true);
        Proceed_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proceed_ButtonActionPerformed(evt);
            }
        });

        Check_Price_Button.setBackground(new java.awt.Color(255, 255, 51));
        Check_Price_Button.setFont(new java.awt.Font("Avignon Pro", 0, 18)); // NOI18N
        Check_Price_Button.setForeground(new java.awt.Color(0, 0, 0));
        Check_Price_Button.setText("See Price");
        Check_Price_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_Price_ButtonActionPerformed(evt);
            }
        });

        TFprice.setEditable(false);
        TFprice.setFont(new java.awt.Font("Avignon Pro", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(Main_Menu_Button1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Clear_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(place_order_button, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CBcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Proceed_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Check_Price_Button)
                                    .addComponent(CBfood, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBqty, 0, 88, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBprice, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TFprice, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TFo_id, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TFo_cust, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addGap(18, 18, 18))))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(TFprice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBfood, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBqty, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBprice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Proceed_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Check_Price_Button))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFo_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFo_cust, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(place_order_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Clear_Button)
                            .addComponent(Main_Menu_Button1))
                        .addGap(77, 77, 77))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBcategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBcategoryMouseClicked
        // TODO add your handling code here:
        
        // Category CB
        /*int category=CBcategory.getSelectedIndex();
        
        if(category==0)
        {
            CBfood.setSelectedIndex(0);
            CBfood.setEnabled(false);
            CBprice.setSelectedIndex(0);
            CBprice.setEnabled(false);
            CBqty.setSelectedIndex(0);
            CBqty.setEnabled(false);   
        }
        else
        {
            
            CBfood.setEnabled(true);
            CBqty.setEnabled(true);
            CBfood.addItem("GG");
        }*/
        
    }//GEN-LAST:event_CBcategoryMouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void Clear_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_ButtonActionPerformed
        // TODO add your handling code here:
        CBcategory.setSelectedIndex(0);
        CBfood.setSelectedIndex(0);
        CBfood.setEnabled(false);
        CBprice.setSelectedIndex(0);
        CBprice.setEnabled(false);
        CBqty.setSelectedIndex(0);
        CBqty.setEnabled(false);
        TFo_cust.setText("");
    }//GEN-LAST:event_Clear_ButtonActionPerformed

    private void Main_Menu_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_Menu_Button1ActionPerformed
        // TODO add your handling code here:
        Main_Menu mm=new Main_Menu();
        mm.setVisible(true);
        dispose();
    }//GEN-LAST:event_Main_Menu_Button1ActionPerformed

    private void place_order_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place_order_buttonActionPerformed
        // TODO add your handling code here:
        
        //Order Placing 
        String o_status="P";
        int o_id=Integer.parseInt(TFo_id.getText());
        String o_item=(String)CBfood.getSelectedItem();
        System.out.println(o_item);
        int o_cust=Integer.parseInt(TFo_cust.getText());
        int o_qty=Integer.parseInt((String)CBqty.getSelectedItem());
        float o_price=Float.parseFloat((String)CBprice.getSelectedItem());
        float o_total=o_qty*o_price;
        if(jRadioButton1.isSelected())
        {
            o_status="O";
        }
        else if(jRadioButton2.isSelected())
        {
            o_status="X";
        }
        
        if(CBfood.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(this,"Please Select an Item (or click Proceed)");
        }
        else if(CBprice.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(this,"Please Check the Price (or click See Price)");
        }
        else if(CBqty.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(this,"Please Select the Qty");
        }
        else
        {
            try
            {
                System.out.println(o_id+"\t"+o_cust+"\t"+o_item+"\t"+o_qty+"\t"+o_total+"\t"+o_status);
                Class.forName("java.sql.DriverManager");
                Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe","root","dhruv");
                java.sql.Statement stmt = con.createStatement();
                String query="insert into orders values('"+o_id+"','"+o_cust+"','"+o_item+"','"+o_qty+"','"+o_price+"','"+o_total+"',now(),'"+o_status+"')";
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(this,"Data Inserted");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
    }//GEN-LAST:event_place_order_buttonActionPerformed

    private void CBcategoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBcategoryMousePressed
           
    }//GEN-LAST:event_CBcategoryMousePressed

    private void CBcategoryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CBcategoryFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_CBcategoryFocusLost

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseMoved

    private void Proceed_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proceed_ButtonActionPerformed
        // TODO add your handling code here:
        
        int category=CBcategory.getSelectedIndex();
        
        if(category==0)
        {
            CBfood.setSelectedIndex(0);
            CBfood.setEnabled(false);
            CBprice.setSelectedIndex(0);
            //CBprice.setEnabled(false);
            CBqty.setSelectedIndex(0);
            CBqty.setEnabled(false);   
        }
        else
        {
            CBfood.setEnabled(true);
            //CBprice.setEnabled(true);
            CBfood.removeAllItems();
            CBprice.removeAllItems();
            CBqty.setEnabled(true);
            CBfood.addItem("------------------Select------------------");
            CBprice.addItem("---------Select---------");
            if(category==1)
            {
                CBfood.addItem("Dahi Papdi Chaat");CBprice.addItem("89.00");
                CBfood.addItem("Aloo Tikki Chaat");CBprice.addItem("110.00");
                CBfood.addItem("French Fries");CBprice.addItem("75.00");
                CBfood.addItem("Paneer Chilli");CBprice.addItem("170.00");
                CBfood.addItem("Dry Manchurian");CBprice.addItem("149.00");
                CBfood.addItem("Vada Pav");CBprice.addItem("40.00");
            }
            else if(category==2)
            {
                CBfood.addItem("Regular Veg Sandwich");CBprice.addItem("99.00");
                CBfood.addItem("Aloo Mutter Sandwich(grill)");CBprice.addItem("135.00");
                CBfood.addItem("Mexican Sandwich (grill)");CBprice.addItem("159.00");
                CBfood.addItem("Cheese Chutney Sandwich");CBprice.addItem("109.00");
                CBfood.addItem("Tandoori Paneer Sandwich");CBprice.addItem("149.00");
                CBfood.addItem("Maska Bun");CBprice.addItem("49.00");
            }
            else if(category==3)
            {
                CBfood.addItem("Margherita Pizza");CBprice.addItem("199.00");
                CBfood.addItem("Special 4 Cheese Pizza");CBprice.addItem("285.00");
                CBfood.addItem("Farm Fresh Pizza");CBprice.addItem("249.00");
                CBfood.addItem("Exotic Veggie Pizza");CBprice.addItem("259.00");
                CBfood.addItem("Cheese Garlic Bread(with Dip)");CBprice.addItem("189.00");
                CBfood.addItem("Italian Pizza(Hand Tossed)");CBprice.addItem("225.00");
            }
            else if(category==4)
            {
                CBfood.addItem("Mac & Cheese");CBprice.addItem("199.00");
                CBfood.addItem("Alfredo Pasta");CBprice.addItem("285.00");
                CBfood.addItem("Arrabiata Pasta");CBprice.addItem("249.00");
                CBfood.addItem("White Sauce Pasta");CBprice.addItem("259.00");
                CBfood.addItem("Pesto Pasta");CBprice.addItem("219.00");
            }
            else if(category==5)
            {
                CBfood.addItem("Espresso Shot");CBprice.addItem("110.00");
                CBfood.addItem("Americano");CBprice.addItem("135.00");
                CBfood.addItem("Cafe Latte");CBprice.addItem("149.00");
                CBfood.addItem("Cafe Mocha");CBprice.addItem("179.00");
                CBfood.addItem("Cappuccino");CBprice.addItem("149.00");
                CBfood.addItem("Flat White");CBprice.addItem("149.00");
                CBfood.addItem("Iced Cafe Mocha");CBprice.addItem("199.00");
                CBfood.addItem("Iced Americano");CBprice.addItem("169.00");
                CBfood.addItem("Classic Cold Coffee");CBprice.addItem("150.00");
                CBfood.addItem("Cafe Frappe");CBprice.addItem("160.00");
                CBfood.addItem("Mocha Frappe");CBprice.addItem("170.00");
                CBfood.addItem("Chocolate Cafe Frappe");CBprice.addItem("170.00");
                CBfood.addItem("Java Chip Frappe");CBprice.addItem("180.00");
                CBfood.addItem("Nutella Mocha Frappe");CBprice.addItem("215.00");
                CBfood.addItem("Masala Tea");CBprice.addItem("55.00");
                CBfood.addItem("Ginger Mint Tea");CBprice.addItem("55.00");
            }
            else if(category==6)
            {
                CBfood.addItem("Oreo Overload Shake");CBprice.addItem("179.00");
                CBfood.addItem("Nutella Shake");CBprice.addItem("229.00");
                CBfood.addItem("Dark Chocolate Shake");CBprice.addItem("199.00");
                CBfood.addItem("Kit-Kat Shake");CBprice.addItem("179.00");
                CBfood.addItem("Belgium Chocolate Shake");CBprice.addItem("249.00");
                CBfood.addItem("Chocolate Shake");CBprice.addItem("169.00");
            }
            else if(category==7)
            {
                CBfood.addItem("Mixed Fruit Juice");CBprice.addItem("139.00");
                CBfood.addItem("Sweet Lime & Kiwi Juice");CBprice.addItem("210.00");
                CBfood.addItem("Orange Juice");CBprice.addItem("125.00");
                CBfood.addItem("Mango Juice");CBprice.addItem("125.00");
                CBfood.addItem("Mixed Berries Smoothie");CBprice.addItem("189.00");
                CBfood.addItem("Strawberry Smoothie");CBprice.addItem("179.00");
            }
        }
    }//GEN-LAST:event_Proceed_ButtonActionPerformed

    private void CBcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBcategoryActionPerformed

    private void CBfoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBfoodMouseClicked
        // TODO add your handling code here:     
        
    }//GEN-LAST:event_CBfoodMouseClicked

    private void Check_Price_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_Price_ButtonActionPerformed
        // TODO add your handling code here:
        int food_index=CBfood.getSelectedIndex();
        CBprice.setSelectedIndex(food_index);
        String price_to_set=(String)CBprice.getSelectedItem();
        TFprice.setText(price_to_set);
    }//GEN-LAST:event_Check_Price_ButtonActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        try {
            Class.forName("java.sql.DriverManager");
            con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe","root","dhruv");
            stmt = con.createStatement();
            String query="select * from orders;";
            ResultSet rs=stmt.executeQuery(query);
            int o_id=0;
            while(rs.next())
            {
                o_id=rs.getInt("o_id");
                System.out.println(o_id+"\n");
            }
            o_id++;
            System.out.println(o_id+"\n");
            TFo_id.setText(Integer.toString(o_id));
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(place_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(place_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(place_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(place_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new place_order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBcategory;
    private javax.swing.JComboBox<String> CBfood;
    private javax.swing.JComboBox<String> CBprice;
    private javax.swing.JComboBox<String> CBqty;
    private javax.swing.JButton Check_Price_Button;
    private javax.swing.JButton Clear_Button;
    private javax.swing.JButton Main_Menu_Button1;
    private javax.swing.JButton Proceed_Button;
    private javax.swing.JTextField TFo_cust;
    private javax.swing.JTextField TFo_id;
    private javax.swing.JTextField TFprice;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton place_order_button;
    // End of variables declaration//GEN-END:variables
}
